

STATE_LEN		=	1	;Ez csak 1 lehet!!!
MOTORCTRL_LEN		=	0	;Ez csak 0-1 lehet!!!

SYSTEM_ACKSTATUS_NUM	=	1
SYSTEM_SSTATUS_NUM	=	1

INPUTS_BYTE_NUM		=	3
OUTPUTS_BYTE_NUM	=	3

LIGHT_NUM		=	0

MOTOR_NUM		=	0
MOTOR_BYTE_NUM		=	0

MOTORSTATUS_LEN		=	0
MOTORINPUTS_LEN		=	0
MOTOROUTPUTS_LEN	=	0
MOTORENC_LEN		=	0
MOTORPOS_LEN		=	0

ANALOG_LEN		=	0
ANALOGBITS_LEN		=	0
